# run-name: Build & release mod ${{ inputs.version }}

# name: build
# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         type: string
#         description: "mod version"
#       java-version:
#         description: "Java version to use (e.g., 17, 21, 24)"
#         required: false
#         default: "21"

# jobs:
#   build:
#     runs-on: ubuntu-latest 
#     steps:
#       - name: Set up JDK
#         uses: actions/setup-java@v3
#         with:
#           java-version: ${{ inputs.java-version }}
#           distribution: "adopt"
  
#       - name: Setup Gradle
#         uses: gradle/gradle-build-action@v2
  
#       - name: Make gradlew executable
#         run: chmod +x ./gradlew
#         shell: bash
  
#       - name: Build with Gradle
#         run: ./gradlew build
#         shell: bash
